'use client';
import { useEffect, useState } from 'react';
import { reportsApi } from '@/lib/api';

export default function ReportsPage() {
    const [reports, setReports] = useState<any[]>([]);
    const [generating, setGenerating] = useState<number | null>(null);
    const [districtId, setDistrictId] = useState(1);
    const [expanded, setExpanded] = useState<number | null>(null);

    useEffect(() => { reportsApi.getHistory().then(setReports).catch(() => { }); }, []);

    async function generate() {
        setGenerating(districtId);
        try {
            await reportsApi.generate(districtId);
            const updated = await reportsApi.getHistory();
            setReports(updated);
        } catch (e: any) {
            alert(`Generation failed: ${e.message}`);
        } finally {
            setGenerating(null);
        }
    }

    const LEVEL_COLOR: Record<string, string> = { critical: '#ff3b3b', high: '#ff6b00', medium: '#ffaa00', low: '#00e676' };

    const S = {
        card: { background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 12, padding: 20 } as React.CSSProperties,
        label: { fontSize: 11, color: '#5a7fa6', textTransform: 'uppercase' as const, letterSpacing: 1, fontFamily: "'JetBrains Mono', monospace" },
    };

    return (
        <div style={{ minHeight: '100vh', background: '#080c14', padding: 24, fontFamily: "'Inter', sans-serif", color: '#e0e8f0' }}>
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
            <div style={{ maxWidth: 900, margin: '0 auto' }}>
                <div style={{ marginBottom: 24 }}>
                    <h1 style={{ fontSize: 24, fontWeight: 700, margin: 0 }}>AI Situation Reports</h1>
                    <p style={{ color: '#5a7fa6', fontSize: 13, margin: '6px 0 0', fontFamily: "'JetBrains Mono', monospace" }}>
                        Generated by Claude API · Structured disaster briefings for district officers
                    </p>
                </div>

                {/* Generate */}
                <div style={{ ...S.card, marginBottom: 20 }}>
                    <div style={{ ...S.label, marginBottom: 14 }}>Generate New Report</div>
                    <div style={{ display: 'flex', gap: 12, alignItems: 'center' }}>
                        <div style={{ flex: 1 }}>
                            <label style={{ ...S.label, display: 'block', marginBottom: 6 }}>District ID</label>
                            <input type="number" value={districtId} min={1} onChange={e => setDistrictId(+e.target.value)}
                                style={{
                                    width: '100%', boxSizing: 'border-box' as const,
                                    background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)',
                                    borderRadius: 8, padding: '10px 12px', color: '#e0e8f0', fontSize: 13, outline: 'none',
                                }} />
                        </div>
                        <button id="generate-report-btn" onClick={generate} disabled={generating !== null} style={{
                            padding: '10px 24px', borderRadius: 10, border: 'none', marginTop: 22,
                            background: generating !== null ? 'rgba(168,139,250,0.2)' : 'linear-gradient(135deg, #a78bfa, #7c3aed)',
                            color: generating !== null ? '#8a9bb0' : '#fff', fontWeight: 600, fontSize: 14,
                            cursor: generating !== null ? 'not-allowed' : 'pointer', whiteSpace: 'nowrap' as const,
                        }}>
                            {generating !== null ? '⏳ Generating...' : '✨ Generate Report'}
                        </button>
                    </div>
                </div>

                {/* Reports List */}
                <div style={S.card}>
                    <div style={{ ...S.label, marginBottom: 16 }}>Report History ({reports.length})</div>
                    {reports.length === 0 ? (
                        <div style={{ textAlign: 'center', padding: 48, color: '#4a5c6e', fontFamily: "'JetBrains Mono', monospace", fontSize: 12 }}>
                            NO REPORTS YET · GENERATE ONE ABOVE
                        </div>
                    ) : (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                            {reports.map((r: any) => {
                                const lc = LEVEL_COLOR[r.risk_level] || '#8a9bb0';
                                const isOpen = expanded === r.id;
                                return (
                                    <div key={r.id} style={{ border: '1px solid rgba(255,255,255,0.07)', borderRadius: 10, overflow: 'hidden' }}>
                                        <button onClick={() => setExpanded(isOpen ? null : r.id)} style={{
                                            width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                                            padding: '14px 16px', background: 'rgba(255,255,255,0.02)', border: 'none', cursor: 'pointer', textAlign: 'left' as const,
                                        }}>
                                            <div>
                                                <span style={{ fontWeight: 600, fontSize: 14, color: '#e0e8f0' }}>{r.district_name || `District #${r.district_id}`}</span>
                                                <span style={{ marginLeft: 10, padding: '2px 8px', borderRadius: 4, background: lc + '22', color: lc, fontSize: 10, fontWeight: 700, fontFamily: "'JetBrains Mono', monospace", textTransform: 'uppercase' as const }}>{r.risk_level || 'N/A'}</span>
                                            </div>
                                            <div style={{ display: 'flex', gap: 16, alignItems: 'center' }}>
                                                <span style={{ fontSize: 11, color: '#4a5c6e', fontFamily: "'JetBrains Mono', monospace" }}>
                                                    {new Date(r.generated_at).toLocaleString('en-IN')}
                                                </span>
                                                <span style={{ color: '#5a7fa6', fontSize: 14 }}>{isOpen ? '▲' : '▼'}</span>
                                            </div>
                                        </button>
                                        {isOpen && (
                                            <div style={{ padding: '0 16px 16px', borderTop: '1px solid rgba(255,255,255,0.05)', background: 'rgba(0,0,0,0.2)' }}>
                                                <pre style={{ margin: '16px 0 0', fontSize: 13, color: '#c0cad8', lineHeight: 1.7, whiteSpace: 'pre-wrap' as const, fontFamily: "'Inter', sans-serif" }}>
                                                    {r.content}
                                                </pre>
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
