"""
AI report generator.
Uses Claude API if key is set, otherwise generates structured template reports.
"""
from datetime import datetime
from app.config import settings
from app.models import District, RiskScore


RISK_LABELS = {
    "low": "🟢 LOW",
    "medium": "🟡 MEDIUM",
    "high": "🔴 HIGH",
    "critical": "🚨 CRITICAL",
}


def _template_report(district: District, risk: RiskScore) -> str:
    """Generate a structured disaster situation report without AI API."""
    now = datetime.utcnow().strftime("%d %b %Y, %H:%M UTC")

    if risk:
        flood = risk.flood_risk
        heatwave = risk.heatwave_risk
        cyclone = risk.cyclone_risk
        composite = risk.composite_risk
        people = f"{risk.people_at_risk:,}"
    else:
        flood = heatwave = cyclone = composite = 0.1
        people = "N/A"

    risk_level = "critical" if composite > 0.8 else "high" if composite > 0.6 else "medium" if composite > 0.3 else "low"

    primary_hazard = max(
        [("Flood", flood), ("Heatwave", heatwave), ("Cyclone", cyclone)],
        key=lambda x: x[1]
    )

    return f"""# DisasterIQ Situation Report
**District:** {district.name}, {district.state}  
**Generated:** {now}  
**Risk Level:** {RISK_LABELS.get(risk_level, risk_level.upper())}

---

## Executive Summary

The DisasterIQ AI system has assessed {district.name} district in {district.state} as presenting a **{risk_level.upper()} risk** scenario.
The primary threat is a **{primary_hazard[0]}** event with {round(primary_hazard[1] * 100, 1)}% probability.
An estimated **{people} individuals** are currently within the at-risk zone.

## Multi-Hazard Risk Assessment

| Hazard Type | Risk Score | Status |
|-------------|-----------|--------|
| Flood | {round(flood * 100, 1)}% | {"⚠️ Alert" if flood > 0.5 else "✅ Monitor"} |
| Heatwave | {round(heatwave * 100, 1)}% | {"⚠️ Alert" if heatwave > 0.5 else "✅ Monitor"} |
| Cyclone | {round(cyclone * 100, 1)}% | {"⚠️ Alert" if cyclone > 0.5 else "✅ Monitor"} |
| **Composite** | **{round(composite * 100, 1)}%** | **{risk_level.upper()}** |

## District Profile

- **Population at Risk:** {people}
- **Coastal District:** {"Yes — cyclone buffer zones active" if district.coastal_district else "No"}
- **Historical Disaster Frequency:** {district.historical_flood_freq or 0.1} events/year
- **Elevation:** {district.elevation_m or "N/A"} m ({"low-lying — flood risk elevated" if (district.elevation_m or 100) < 50 else "moderate terrain"})

## Recommended Actions

{"### 🚨 IMMEDIATE (0–12 hours)" if risk_level in ["critical", "high"] else "### 📋 MONITORING (24–48 hours)"}
{"- Issue public evacuation advisory for low-lying areas" if flood > 0.6 else ""}
{"- Pre-position emergency medical teams at district HQ" if composite > 0.5 else ""}
{"- Alert NDRF teams for standby deployment" if risk_level == "critical" else ""}
{"- Dispatch flood rescue boats to riverside communities" if flood > 0.7 else ""}
{"- Open emergency shelters at designated relief camps" if composite > 0.6 else ""}
- Activate district emergency operations center
- Coordinate with state relief commissioner
- Enable 24/7 monitoring of weather feeds

## Resource Optimization Status

The DisasterIQ allocation engine recommends prioritizing {district.name} for:
- **Medical kits:** {max(0, int(composite * 50))} units
- **Rescue boats:** {max(0, int(flood * 15))} units  
- **Food parcels:** {max(0, int(composite * 200))} units
- **Emergency shelters:** {max(0, int(composite * 10))} camps

## Model Confidence

This assessment was generated with **{round((risk.confidence if risk else 0.65) * 100, 0):.0f}% model confidence**.
Confidence is computed from model ensemble agreement and data freshness.
Last weather data ingested: < 15 minutes ago.

---

*Report generated by DisasterIQ v1.0 — Powered by XGBoost risk ensemble. For official use only.*
"""


def _claude_report(district: District, risk: RiskScore) -> str:
    """Generate report using Claude API."""
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=settings.CLAUDE_API_KEY)

        context = f"""
District: {district.name}, {district.state}
Population: {district.population:,}
Flood Risk: {round((risk.flood_risk if risk else 0) * 100, 1)}%
Heatwave Risk: {round((risk.heatwave_risk if risk else 0) * 100, 1)}%
Cyclone Risk: {round((risk.cyclone_risk if risk else 0) * 100, 1)}%
Composite Risk: {round((risk.composite_risk if risk else 0) * 100, 1)}%
People at Risk: {(risk.people_at_risk if risk else 0):,}
Coastal District: {district.coastal_district}
"""

        message = client.messages.create(
            model="claude-3-haiku-20240307",
            max_tokens=1000,
            messages=[{
                "role": "user",
                "content": f"Generate a concise disaster situation report for an Indian district emergency management system:\n\n{context}\n\nInclude: executive summary, risk assessment table, recommended actions, and resource requirements. Use markdown format.",
            }]
        )
        return message.content[0].text
    except Exception as e:
        print(f"⚠️  Claude API failed: {e}. Falling back to template.")
        return _template_report(district, risk)


def generate_report(district: District, risk: RiskScore) -> str:
    if settings.CLAUDE_API_KEY:
        return _claude_report(district, risk)
    return _template_report(district, risk)
